[versions]
checkerframework = "3.26.0"
fastutil = "8.5.3"
netty = "4.1.84.Final"
gson = "2.3.1" # Provided by Spigot 1.8.8
msgpack = "0.6.12"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checkerframework" }

fastutil-long-common = { group = "com.nukkitx.fastutil", name = "fastutil-long-common", version.ref = "fastutil" }
fastutil-long-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-long-object-maps", version.ref = "fastutil" }
fastutil-int-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-int-object-maps", version.ref = "fastutil" }
fastutil-object-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-object-int-maps", version.ref = "fastutil" }

netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-transport-raknet = { group = "org.cloudburstmc.netty", name = "netty-transport-raknet", version = "1.0.0.CR1-SNAPSHOT" }

jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version = "0.9.3" }
natives = { group = "com.nukkitx", name = "natives", version = "1.0.3" }
math = { group = "org.cloudburstmc.math", name = "immutable", version = "2.0-SNAPSHOT" }
nbt = { group = "org.cloudburstmc", name = "nbt", version = "3.0.0.Final" }
lmbda = { group = "org.lanternpowered", name = "lmbda", version = "2.0.0" }
msgpack = { group = "org.msgpack", name = "msgpack", version.ref = "msgpack" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

snappy = { group = "io.airlift", name = "aircompressor", version = "0.21" }

[plugins]
checkerframework = { id = "org.checkerframework", version = "0.6.24" }
lombok = { id = "io.freefair.lombok", version = "6.6.3" }
